### ISSUE TITLE
Add score function including prior

### ISSUE THREAD

**Issue by MichaelClerx** [martinjrobins/pints#19]
Martin wrote:

"_[C]an you create a score function that depends on the parameters (i.e. incorporate a prior into the score function)?_"

**Comment by MichaelClerx** [comment]
Won't be required for uniform priors I suppose, so mostly useful for echem problems?

**Comment by martinjrobins** [comment]
probably useful for other problems too, if you know something about the params.

**Comment by mirams** [comment]
I guess for starting MCMC chains you want the evaluation of Likelihood * Prior sometimes. We won't always have uniform in e-phys either... especially when scaling params, just the first thing we tried.

**Comment by martinjrobins** [comment]
@MichaelClerx : how do you see this working with the new structure? I used to have a class `prior` that contained the parameters to be fitted, and their bounds (min/max), and their prior distributions (normal/uniform), and this was separate from the model itself. In the new structure you have the parameters embedded in the models. Were you thinking that prior information goes in the model as well?

**Comment by MichaelClerx** [comment]
@martinjrobins good question! I think the `prior` can still be a separate object, just like `boundaries` is!

Sorry I haven't restored all your previous work yet, working on a paper now but will get back to it asap.

**Comment by MichaelClerx** [comment]
@mirams The optimisers work with any score function object that implements the (very simple) `MeasureOfFit` interface (https://github.com/martinjrobins/pints/blob/master/pints/_score.py#L12-L24).

It should be quite easy to define all sorts of score functions that implement this, including ones that multiply a likelihood by a prior

**Comment by MichaelClerx** [comment]
This is now possible as follows:

```
# Define a log likelihood
log_likelihood = pints.GaussianLogLikelihood(problem)

# Define a prior
prior = pints.UniformPrior([0.01, 400, noise*0.1], [0.02, 600, noise*100])

# Create a Bayesian log-likelihood (log(prior) + likelihood)
bayesian_log_likelihood = pints.BayesianLogLikelihood(prior, log_likelihood)

# Wrap a score function around it!
score = pints.LogLikelihoodBasedError(bayesian_log_likelihood)
```

First step adds the noise parameter, defines the log-likelihood as in Ross' paper. Second step defines a uniform prior (can be based on Boundaries object, or non-uniform). Third step combines them into a bayesian sum of log-likelihoods, and the final one just multiplies it all by -1 so that minimising it gives the best fit
