### ISSUE TITLE
Work out how to use Seaborn/CMA-ES without having it affect matplotlib too much

### ISSUE THREAD

**Issue by MichaelClerx** [martinjrobins/pints#20]
Libraries shouldn't affect other libraries, it would be pretty rubbish if people imported `pints` and then found `matplotlib`'s behavior had changed because of the `cma` and `seaborn` modules.

**Comment by MichaelClerx** [comment]
https://github.com/CMA-ES/pycma/issues/17

**Comment by MichaelClerx** [comment]
https://stackoverflow.com/questions/25393936/how-can-i-use-seaborn-without-changing-the-matplotlib-defaults

**Comment by nikohansen** [comment]
Should be addressed with commit a121b33a3e1fc2a061b0351d2117932d08cc148a. If there is still disturbing interference, don't hesitate to reopen.

**Comment by MichaelClerx** [comment]
Thanks!
