### ISSUE TITLE
adaptive covariance MCMC functionality

### ISSUE THREAD

**Issue by martinjrobins** [martinjrobins/pints#4]
need a function/class that takes a model, a set of parameters, prior information and a data set and returns distributions on the parameters using adaptive covariance MCMC

**Comment by martinjrobins** [comment]
and for hierarchical MCMC a set of hyperparameters as well.....!

**Comment by MichaelClerx** [comment]
Starting on a simple implementation of the non-hierarchical version used by ross/dave

**Comment by martinjrobins** [comment]
7deed9 adds an adaptive covariance mcmc algorithm and output plotting using a script from Sanmitra (using python Seaborn plotting library). Still playing around with it to ensure it is working

**Comment by martinjrobins** [comment]
2aa0b35ec6b11c844d51e34c31f4443f7fa7ce97 updates mcmc routine to use the model params for an initial guess. Now you can call the cmaes routine (which updates the model params with best fit), then the mcmc straight away

**Comment by MichaelClerx** [comment]
It's online now, but seems to have a bug in it

**Comment by MichaelClerx** [comment]
Nope, not buggy: Turns out the log-likelihood function gets biased for very noisy signals (esp. with low sampling rates).

See demo `example_mcmc.py` from e54ec150af99b0f9bf825ac1413794fc6fb933f3
