### ISSUE TITLE
Set up travis-ci.org

### ISSUE THREAD

**Issue by MichaelClerx** [martinjrobins/pints#46]
@martinjrobins Jonathan Cooper suggested we set up this repo to have automated testing with Travis (travis-ci.org).
I had a look but it tells me I don't have the authority. Would you like to give this a go?

**Comment by martinjrobins** [comment]
I've added the travis-ci integration, and setup on the travis side. Now we just need a .travis.yaml file, how does the python testing work, what commands do I need to run all the tests?

**Comment by MichaelClerx** [comment]
Brilliant! You can use the `run-tests.sh` file. That doesn't include project tests, but I think that's for the best (they should move to their own repo in the long run anyway).

**Comment by martinjrobins** [comment]
all done and all tests passing on travis (testing on Ubuntu 14.04, Python version 2.7 using pip to install deps, which are listed in requirements.txt)
