### ISSUE TITLE
allow forward models to output the model in STAN language

### ISSUE THREAD

**Issue by martinjrobins** [martinjrobins/pints#5]
Need to implement each model in the STAN language. Perhaps have a member function for each model that returns the STAN language representation as a string?

**Comment by MichaelClerx** [comment]
Will get to this as soon as we finalise what our stan models should look like :-)

**Comment by MichaelClerx** [comment]
Am currently adding models in Myokit (because i need to have these anyway) and generating STAN, will be useful for creating the STAN generating methods

**Comment by MichaelClerx** [comment]
I think the best way to do this would be:

1. Figure out what the requirements for a stan "model" are, using one of Ben's example files. Note this will be more than just equations, and will include some solver (stan calls to cvodes) and protocol.
2. Create a new abstract class that can be used to provide the above information.
3. Create a test class that extends it
4. Create a PyStan based file to run experiments (very simple probably...) using anything that extends our abstract class
5. Write some tests!

**Comment by martinjrobins** [comment]
as for #6 , lets close this for now until someone has more success using STAN
