### ISSUE TITLE
STAN interface

### ISSUE THREAD

**Issue by martinjrobins** [martinjrobins/pints#6]
Need a function/class that takes a model and a data set, passes this into STAN to be solved (using HMC) and returns distributions on the parameters

**Comment by martinjrobins** [comment]
3a96a06 adds the ability to get a STAN model from the ECModel class. This model doesnt do much yet, just runs the simulation

**Comment by MichaelClerx** [comment]
Hi @martinjrobins ! I can see two ways to resolve this issue:

1. Declare this outside the scope of Pints
2. Add a class `StanCompatibleModel extends Model` that also provides a `stan_code()` method.

Option 2 is only useful if we envision doing STAN stuff directly in Pints though!

**Comment by martinjrobins** [comment]
Unless Ben gets STAN working well on these types of models, I doubt we will use it, so lets just close it until something changes.
