### ISSUE TITLE
test script: STAN versus adaptive covariance MCMC

### ISSUE THREAD

**Issue by martinjrobins** [martinjrobins/pints#7]
need a test script that compares STAN versus our own adaptive covariance MCMC, using 

1. Electrochem FeIII dataset
2. Kylie's dataset (or other, as I don't have this yet...)

**Comment by martinjrobins** [comment]
I think that we are dropping STAN for the moment, so will close this

**Comment by MichaelClerx** [comment]
Ok! As long as we remember we did this and how to explain it didn't work :-)
