### ISSUE TITLE
Restriction in ForwardModel.simulate() output when we expand from SingleSeriesProblem()

### ISSUE THREAD

**Issue by chonlei** [martinjrobins/pints#77]
Just come to my mind that later we might want to have some restriction in the ForwardModel.simulat(). For SingleSeriesProblem() we should be fine, but when we do multiple series later if we do. Then we might want to restrict the output to be row-wise or column-wise.

I guess for example if we never specify this (e.g. raise the error at the very beginning) then it would be very hard/annoying for the user to spot on they should just do a transpose on their output to make the whole thing works. For us would be easy, but for those who never use it before, it would be hard for them.

**Comment by MichaelClerx** [comment]
I think we're sticking with models that output a single series. Multi series problems would be created from multiple experiment sets (e.g. a hierarchical mcmc problem). When we start doing those, we can decide what the best order is and write a note in the relevant docstring specifying what the output format is.
At the moment, everything lives in a 1d space, so we don't have a concept of rows or columns (everything has shape (n), not (n,1) or (1,n))

**Comment by mirams** [comment]
Worth bearing in mind. We could easily end up with wanting to fit e.g. Voltage and Calcium traces from a single simulation, without this being related to hierarchical problems.

**Comment by MichaelClerx** [comment]
Absolutely, but we have lots of other small design decisions to make once we start doing those :-)
